version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: basic_nestjs
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: v4wedsavhoqwd
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always

